[output]
copy = true
file = ""
stdout = true

[[section]]
max_depth = -1
title = "PROJECT STRUCTURE"
type = "tree"
use_gitignore = true

[[section]]
body = "Describe what you want the assistant to do here."
title = "REQUEST"
type = "text"

[[section]]
path = "references/DESIGN.md"
title = "DESIGN.MD"
type = "file"